import type {Metadata} from "next"
import "./globals.css"
import SessionWrapper from "../components/SessionWrapper"
import {ReactQueryClientProvider} from "@/src/components/ReactQueryClientProvider"
import {ClubsProvider} from "./context/ClubsContext"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<SessionWrapper>
			<ReactQueryClientProvider>
				<ClubsProvider>
					<html lang="en">
						<body>
							<main className="flex justify-center items-center h-screen">
								<div className="bg-[#00000084] z-10 relative backdrop-blur-md h-3/4 w-3/4 rounded-lg">
									{children}
								</div>
							</main>
						</body>
					</html>
				</ClubsProvider>
			</ReactQueryClientProvider>
		</SessionWrapper>
	)
}
