import type {Metadata} from "next"
import "./globals.css"
import SessionWrapper from "../components/SessionWrapper"
import {ReactQueryClientProvider} from "@/src/components/ReactQueryClientProvider"
import {ClubsProvider} from "./context/ClubsContext"
import {ClubProvider} from "./context/ClubContext"
import {PlayerProvider} from "./context/PlayersContext"
import Header from "../components/custom/Header"
import Footer from "../components/custom/Footer"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<SessionWrapper>
			<ReactQueryClientProvider>
				<ClubsProvider>
					<ClubProvider>
						<PlayerProvider>
							<html lang="en">
								<body className="h-screen">
									<div className="background">
										<Header />
										<main>{children}</main>
										<Footer />
									</div>
								</body>
							</html>
						</PlayerProvider>
					</ClubProvider>
				</ClubsProvider>
			</ReactQueryClientProvider>
		</SessionWrapper>
	)
}
